### ISSUE TITLE
Indentation is all over the place

### ISSUE THREAD

**Issue by TheByteSizeDev** [crisneames/daily-journal#3]
Indentation and nicely styled code is important for readability. Here's a good article on it to help you out!

[Style Guide](https://www.w3schools.com/html/html5_syntax.asp)

https://github.com/crisneames/daily-journal/blob/62a85dfc23ea8c9be9630adb76793e8c4164bfce/index.html#L14-L18

**Comment by crisneames** [comment]
fixed
