### ISSUE TITLE
Not seeing the closing tag for this section

### ISSUE THREAD

**Issue by TheByteSizeDev** [crisneames/daily-journal#4]
This `<section>` tab seems to be missing a closing tag? Should be on the line under the `<form>` tag but I don't see it. When you start getting the hang of formatting your code and using indentions it will help a lot with being able to see when you are missing closing tags.

https://github.com/crisneames/daily-journal/blob/62a85dfc23ea8c9be9630adb76793e8c4164bfce/index.html#L16

**Comment by crisneames** [comment]
fixed
